import { StyleSheet, Dimensions, StatusBar } from 'react-native';

export const style = StyleSheet.create({
    scroll: {
        flex: 1,
    },
    img: {
        flex: 1,
        height: Dimensions.get('window').height + StatusBar.currentHeight,
        width: Dimensions.get('window').width,
        justifyContent: 'center',
        alignItems: 'center',
    },
    container: {
        width: 0.85 * Dimensions.get('window').width,
        justifyContent: 'space-around',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 25,
    },
    title: {
        color: '#FFF',
        fontFamily: 'Montserrat-Bold',
        fontSize: 28,
    },
    containerInput: {
        width: '100%',
        gap: 20,
    },
    input: {
        backgroundColor: '#FFFFFF66',
        borderRadius: 50,
        paddingVertical: 15,
        paddingHorizontal: 25,
        fontFamily: 'Montserrat-Medium',
        fontSize: 15,
        color: '#FFF',
    },
    btnEntrar: {
        backgroundColor: '#8200F5',
        borderRadius: 50,
        width: '100%',
        paddingVertical: 15,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 10,
    },
    btnEntrarText: {
        color: '#FFF',
        fontFamily: 'Montserrat-Bold',
        fontSize: 20,
    },
    containerLine: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        width: '100%',
    },
    line: {
        backgroundColor: '#FFF',
        width: '40%',
        height: 1,
        borderRadius: 50,
    },
    lineText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 18,
    },
    containerBtn: {
        gap: 15,
    },
    btnGoogle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 50,
        paddingVertical: 15,
        paddingHorizontal: 25,
        elevation: 10,
    },
    googleImg: {
        width: 23,
    },
    googleText: {
        color: '#000',
        fontWeight: '700',
        fontSize: 18,
    },
    btnApple: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 15,
        paddingHorizontal: 25,
        borderRadius: 50,
        backgroundColor: '#000',
        elevation: 10,
    },
    appleContent: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 18,
    },
    btnCriarConta: {
        backgroundColor: '#8200F5',
        borderRadius: 50,
        paddingVertical: 15,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 10,
    },
    btnCriarContaText: {
        color: '#FFF',
        fontFamily: 'Montserrat-Bold',
        fontSize: 20,
    },
});
