import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
    principal: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        height: '50vh',
        marginTop: 50,
    },
    header: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 25,
    },
    headerContent: {
        alignItems: 'center',
    },
    name: {
        fontFamily:'Montserrat-ExtraBold',
        fontSize: 25,
        color: '#000',
    },
    pronome: {
        fontFamily:'Montserrat-Medium',
        fontSize: 22,
        color: '#4D4D4D',
    },
    img: {
        width: 300,
        height: 300,
        borderRadius: 250,
        marginTop: 30,
        marginBottom: 30,
    },
    imgUser: {
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        borderRadius: 250,
        width: 300,
        height: 300,
        marginTop: 30,
        marginBottom: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    carac: {
        marginBottom: 60,
        fontFamily:'Montserrat-Medium',
        fontWeight: '500',
        fontSize: 25,
        color: '#000',
    },
    info: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 25,
    },
    title: {
        fontFamily:'Roboto-Bold',
        fontWeight: '700',
        fontSize: 20,
        textTransform: 'capitalize',
        color: '#000',
    },
    idade: {
        fontFamily:'Roboto',
        fontWeight: '700',
        fontSize: 20,
        color: 'rgba(0, 0, 0, 0.6)',
    },
    genero: {
        fontFamily:'Roboto',
        fontWeight: '700',
        fontSize: 20,
        textTransform: 'capitalize',
        color: 'rgba(0, 0, 0, 0.6)',
    },
    descricaoContainer: {
        paddingVertical: 15,
        paddingHorizontal: 25,
        marginTop: 20,
        marginBottom: 50,
        gap: 15,
    },
    descricao: {
        fontFamily:'Roboto',
        fontWeight: '700',
        fontSize: 18,
        lineHeight: 28,
        textTransform: 'capitalize',
        color: 'rgba(0, 0, 0, 0.6)',
    },
    bottomSheet: {
        paddingHorizontal: 40,
        alignItems: 'flex-start',
        paddingVertical: 20,
        gap: 40,
    },
    bottomSheetBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 30,
    },
    bottomSheetText: {
        color: '#000',
        fontSize: 18,
        fontWeight: '700',
    },
});
